quarkiverse/quarkus-openapi-generator

- README.md
Added warning to prevent users from adding duplicate `quarkus-maven-plugin` entry to their pom.xml files.
> Added warning to README.md

- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/SpecConfig.java
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java
- deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/SpecConfigTest.java
- deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapperTest.java
- integration-tests/src/main/resources/application.properties
- integration-tests/src/test/java/io/quarkiverse/openapi/generator/it/WiremockPetStore.java
Closes #7 
Signed-off-by: Ricardo Zanini <ricardozanini@gmail.com>
> Fix #7 - Correct handling paths on Windows machines

- .lgtm.yml
Signed-off-by: Ricardo Zanini <zanini@redhat.com>
> Install LGTM configuration file

- deployment/pom.xml
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java
- deployment/src/main/resources/templates/enumClass.qute
- deployment/src/main/resources/templates/enumOuterClass.qute
- deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapperTest.java
- deployment/src/test/resources/openapi/issue-28.yaml
- pom.xml
> Fix #28 - Add Enum Outer Class template and values cache

- README.md
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CodegenConfig.java
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/ModelCodegenConfigParser.java
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/SpecInputModel.java
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/QuarkusJavaClientCodegen.java
- deployment/src/main/resources/application.properties
- deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/CodegenConfigTest.java
- deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapperTest.java
> Fix #40 - Add verbose codegen configuration and instructions for maven runs

- README.md
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CodegenConfig.java
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/SpecInputModel.java
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java
- deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapperTest.java
- integration-tests/example-project/src/main/resources/application.properties
- integration-tests/example-project/src/test/java/io/quarkiverse/openapi/generator/it/SimpleOpenApiTest.java
> Fix #62 - add filename if using default basePackage

- README.md
Its code quarkus not Quarkus Starter :)
> minor wording fix

- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorStreamCodeGen.java
File name path  might be just a file name or a relative path including directories. 
This PR creates the directories in case they do not exist yet.
> If file name is a path and not just a name, dirs should be created

- .github/project.yml
- README.md
PR for a prerelease of 0.8.0 version
> Prerelease 0.8.0 version

- deployment/src/main/resources/templates/enumClass.qute
- deployment/src/main/resources/templates/enumOuterClass.qute
- integration-tests/generation-tests/src/test/java/io/quarkiverse/openapi/generator/it/WiremockPetStore.java
No code changes, but only modified template for enum.
> fix(): missing @JsonCreator annotation for inner enum

- README.md
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CodegenConfig.java
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java
- deployment/src/main/resources/templates/api.qute
- deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapperTest.java
- integration-tests/example-project/src/main/java/org/acme/openapi/weather/api/provider/CountProvider.java
- integration-tests/example-project/src/main/resources/application.properties
> feat(#108): support custom register provider

- README.md
> Add badges inline with other quarkiverse projects

- deployment/src/main/resources/templates/api.qute
- deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapperTest.java
- deployment/src/test/resources/openapi/petstore-openapi-custom-register-provider.json
- integration-tests/example-project/src/main/openapi/open weather customer register provider.yaml
- integration-tests/example-project/src/main/resources/application.properties
There is a bug actually in the released 0.11.0.
I'll still need to write / correct a few tests for this.
> Import org.eclipse.microprofile.rest.client.annotation.RegisterProvider when custom-register-providers is used

- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java
- integration-tests/ignore/src/test/java/io/quarkiverse/openapi/generator/it/IgnoreTest.java
Cherry-picking https://github.com/quarkiverse/quarkus-openapi-generator/pull/184
> [quarkus2][issue-183] Fixed order of imports

- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java
- integration-tests/ignore/src/test/java/io/quarkiverse/openapi/generator/it/IgnoreTest.java
Fixes: https://github.com/quarkiverse/quarkus-openapi-generator/issues/183
> [issue-183] Fixed order of imports

- README.md
Fixes: https://github.com/quarkiverse/quarkus-openapi-generator/issues/191
PR to support Quarkus 3 in `main` branch: https://github.com/quarkiverse/quarkus-openapi-generator/pull/190
> Added info about Quarkus 3 to README.md

- pom.xml
Fix https://github.com/quarkiverse/quarkus-openapi-generator/issues/207.
> Updated Quarkus to 2.15.1

- deployment/src/main/resources/templates/enumClass.qute
- deployment/src/main/resources/templates/pojo.qute
- integration-tests/array-enum/pom.xml
- integration-tests/array-enum/src/main/openapi/array-enum.yaml
- integration-tests/array-enum/src/test/java/io/quarkiverse/openapi/generator/it/ArrayEnumTest.java
- integration-tests/pom.xml
Fixes: https://github.com/quarkiverse/quarkus-openapi-generator/issues/205
Needs to be cherry-picked to `quarkus2` branch.
> Added support to enum arrays

- deployment/src/main/resources/templates/enumClass.qute
- integration-tests/enum-property/pom.xml
- integration-tests/enum-property/src/main/openapi/enum-property.yaml
- integration-tests/enum-property/src/test/java/io/quarkiverse/openapi/generator/it/EnumPropertyTest.java
- integration-tests/pom.xml
Backport of https://github.com/quarkiverse/quarkus-openapi-generator/pull/215.
> quarkus2 issue-214 Fixed enum serialization (#215)

- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/SpecItemConfig.java
Fixes: https://github.com/quarkiverse/quarkus-openapi-generator/issues/220
> Fixed issue that prevented the app from starting when "base-package" property was not set

- README.md
- deployment/pom.xml
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CodegenConfig.java
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/SpecItemConfig.java
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java
- deployment/src/main/resources/templates/api.qute
- integration-tests/pom.xml
- integration-tests/return-response/pom.xml
- integration-tests/return-response/src/main/openapi/model-simple-openapi.yaml
- integration-tests/return-response/src/main/openapi/response-simple-openapi.yaml
- integration-tests/return-response/src/main/resources/application.properties
- integration-tests/return-response/src/test/java/io/quarkiverse/openapi/generator/it/ReturnResponseTest.java
Backport of https://github.com/quarkiverse/quarkus-openapi-generator/pull/219#event-8171662613
> [quarkus2] Added "return-response" property to return `Response` instead of a model (#219)

- README.md
Backport of https://github.com/quarkiverse/quarkus-openapi-generator/pull/231
> Add Apicurio reference in the README (#231)

- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/template/QuteTemplatingEngineAdapter.java
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/QuarkusJavaClientCodegen.java
- deployment/src/main/resources/templates/auth/compositeAuthenticationProvider.qute
- runtime/src/main/java/io/quarkiverse/openapi/generator/providers/AbstractAuthProvider.java
- runtime/src/main/java/io/quarkiverse/openapi/generator/providers/ApiKeyAuthenticationProvider.java
- runtime/src/main/java/io/quarkiverse/openapi/generator/providers/BasicAuthenticationProvider.java
- runtime/src/main/java/io/quarkiverse/openapi/generator/providers/BearerAuthenticationProvider.java
- runtime/src/main/java/io/quarkiverse/openapi/generator/providers/OAuth2AuthenticationProvider.java
Backport of https://github.com/quarkiverse/quarkus-openapi-generator/pull/248
> [quarkus2] Changed oauth2AuthenticationProvider.qute to not be generated (#248)

- runtime/src/main/resources/META-INF/quarkus-extension.yaml
See context: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Quarkiverse.20Extension/near/322455521
> Change the extension category

- runtime/src/main/resources/META-INF/quarkus-extension.yaml
See context: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Quarkiverse.20Extension/near/322455521
Backport of: https://github.com/quarkiverse/quarkus-openapi-generator/pull/254
> [quarkus2] Change the extension category (#254)

- deployment/pom.xml
- deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/template/QuteTemplatingEngineAdapterTest.java
- integration-tests/skip-validation/src/test/java/io/quarkiverse/openapi/generator/it/AWXTest.java
Backport of: https://github.com/quarkiverse/quarkus-openapi-generator/pull/273
> feat: Bump org.openapitools to 6.4.0 (#273)

- .github/workflows/release.yml
Backport of https://github.com/quarkiverse/quarkus-openapi-generator/pull/284
> Bump crazy-max/ghaction-import-gpg from 3 to 5 (#284)

- .github/workflows/release.yml
Due to: https://github.com/quarkiverse/quarkus-openapi-generator/actions/runs/4929042343/jobs/8808209605?pr=332
> Fix the "release" workflow

- deployment/src/main/resources/templates/api.qute
Cherry-picked from:
- https://github.com/quarkiverse/quarkus-openapi-generator/pull/336
> Fixed javadoc (#336)

- .github/workflows/build.yml
Fixes: https://github.com/quarkiverse/quarkus-openapi-generator/issues/188
> Added checks for import order and code format to CI

- .github/workflows/pr-backporting.yml
Fixes: https://github.com/quarkiverse/quarkus-openapi-generator/issues/367
> Added PR Backporting action

- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CodegenConfig.java
- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java
- deployment/src/main/resources/templates/api.qute
- integration-tests/mutiny/pom.xml
- integration-tests/mutiny/src/main/openapi/quarkus-simple-openapi.yaml
- integration-tests/mutiny/src/main/resources/application.properties
- integration-tests/mutiny/src/test/java/io/quarkiverse/openapi/generator/it/MutinyTest.java
- integration-tests/pom.xml
Fixes https://github.com/quarkiverse/quarkus-openapi-generator/issues/402
> Fixes the "mutiny" config

- .github/workflows/stale_issues.yml
Fixes https://github.com/quarkiverse/quarkus-openapi-generator/issues/390
> Added "Close Stale Issues" GitHub Action

- .github/workflows/stale_issues.yml
With this PR, the bot will put a comment when an issue/PR is closed or set as stale.
> Added stale and close messages to actions/stale GHA

- integration-tests/pom.xml
This PR sorts the integration test modules in alphabetical order.
> Sorted integration test modules

- CONTRIBUTING.md
- README.md
- pull_request_template.md
This PR adds information for contributors and maintainers.
> Added CONTRIBUTING.md

- README.md
Sorry about that @hbelmiro, I forgot this one.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it …
> Adjust documentation for config-key feature

- deployment/pom.xml
- deployment/src/main/resources/templates/libraries/microprofile/enumClass.qute
- deployment/src/main/resources/templates/libraries/microprofile/pojo.qute
- deployment/src/main/resources/templates/libraries/microprofile/pojoQueryParam.qute
- deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapperTest.java
- integration-tests/github/pom.xml
- integration-tests/pom.xml
This test that a modified version of github spec compiles. 
The changes are related with "+1", "-1" and "*" values. 
See issue https://github.com/OpenAPITools/openapi-generator/issues/16531
> Adding github spec to IT in order to verify it compiles

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/quarkus-snapshot.yaml
- .github/workflows/release.yml
(cherry picked from commit dd59835ce61812fe906172eccca34d46c54d3859)
> Bump actions/checkout from 3 to 4 (#477)

- deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java
- deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapperTest.java
- integration-tests/security/src/main/resources/application.properties
Fixes [https://github.com/quarkiverse/quarkus-openapi-generator/issues/496](https://github.com/quarkiverse/quarkus-openapi-generator/issues/496)
> issue-496 make the code consistent with documentation and improve test

- deployment/src/main/resources/templates/libraries/microprofile/enumClass.qute
- deployment/src/main/resources/templates/libraries/microprofile/enumOuterClass.qute
Fixes: https://github.com/quarkiverse/quarkus-openapi-generator/issues/421
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release …
> Rename fromValue to fromString in Enum classes

- .github/workflows/preview.yml
<details>
<summary>
</summary> …
> Fix action comments after building docs

- deployment/src/main/resources/templates/libraries/microprofile/auth/compositeAuthenticationProvider.qute
- runtime/src/main/java/io/quarkiverse/openapi/generator/providers/OAuth2AuthenticationProvider.java
This PR fixes a compilation error that could happen when using RESTEasy Reactive.
> Fixed compilation error

- .github/project.yml
> Prepare release 2.2.14

- .github/project.yml
> Prepare Release 1.3.14

- .github/workflows/codeql.yml
(cherry picked from commit c66600e12436b1ac1ddfe20ad70585108cc60ec4)
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. …
> Bump github/codeql-action from 2 to 3 (#595)

- .github/workflows/preview.yml
<details>
<summary>
</summary> …
> :closed_lock_with_key: Updating surge token

- deployment/src/main/resources/templates/libraries/microprofile/pojo.qute
Fixes https://github.com/quarkiverse/quarkus-openapi-generator/issues/633
> Do not include null value in request

- README.md
<details>
<summary>
</summary> …
> Update latest documentation link

- client/deployment/pom.xml
- client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java
- client/deployment/src/main/resources/templates/libraries/microprofile/pojo.qute
- client/deployment/src/main/resources/templates/libraries/microprofile/pojoQueryParam.qute
<details>
<summary>
</summary> …
> Bump version.org.openapitools from 7.4.0 to 7.5.0

- .github/workflows/snapshot_deploy.yml
<details>
<summary>
</summary> …
> Add deploy snapshot workflow

- client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/template/OpenApiNamespaceResolver.java
Fixes https://github.com/quarkiverse/quarkus-openapi-generator/issues/742
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release …
> [Fix #742]

- docs/modules/ROOT/pages/includes/quarkus-openapi-generator.adoc
Fixes #752 
<details>
<summary>
</summary> …
> Update the documentation

- client/deployment/src/main/resources/templates/libraries/microprofile/model.qute
- client/deployment/src/main/resources/templates/libraries/microprofile/pojo.qute
- client/integration-tests/simple/src/main/openapi/quarkus-simple-openapi.yaml
Fixes #779 
<details>
<summary>
</summary> …
> Add java.util.Set on imports

- client/deployment/pom.xml
- client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/QuarkusJavaClientCodegen.java
- client/deployment/src/main/resources/templates/libraries/microprofile/api.qute
- client/deployment/src/main/resources/templates/libraries/microprofile/model.qute
- client/deployment/src/main/resources/templates/libraries/microprofile/pojo.qute
- client/deployment/src/main/resources/templates/libraries/microprofile/pojoQueryParam.qute
- client/integration-tests/pom.xml
<details>
<summary>
</summary> …
> Upgrade org.openapitools to 7.8.0

- client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CodegenConfig.java
- client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CommonItemConfig.java
- client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java
- client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java
- client/deployment/src/main/resources/templates/libraries/microprofile/api.qute
- client/deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapperTest.java
- client/deployment/src/test/resources/openapi/simple-openapi.json
- client/integration-tests/mutiny/src/main/openapi/quarkus-multiple-endpoints-openapi.yaml
- client/integration-tests/mutiny/src/main/openapi/quarkus-multiple-endpoints-wrong-configuration-openapi.yaml
- client/integration-tests/mutiny/src/main/resources/application.properties
- client/integration-tests/mutiny/src/test/java/io/quarkiverse/openapi/generator/it/MutinyTest.java
- client/integration-tests/return-response/src/main/openapi/mutiny-multi-return-response-false-string-simple-openapi.yaml
- client/integration-tests/return-response/src/main/openapi/mutiny-multi-return-response-false-void-simple-openapi.yaml
- client/integration-tests/return-response/src/main/openapi/mutiny-multi-return-response-true-string-simple-openapi.yaml
- client/integration-tests/return-response/src/main/openapi/mutiny-multi-return-response-true-void-simple-openapi.yaml
- client/integration-tests/return-response/src/main/resources/application.properties
- client/integration-tests/return-response/src/test/java/io/quarkiverse/openapi/generator/it/ReturnResponseTest.java
- docs/modules/ROOT/pages/includes/resteasy-support.adoc
fixes #782 
- [x ] Pull Request contains link to the issue
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a …
> #782: Support for Mutiny Return Type on Specific Endpoints

- client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java
- client/integration-tests/config-key/src/main/resources/application.properties
- client/integration-tests/config-key/src/test/java/io/quarkiverse/openapi/generator/configkey/QuarkusConfigKeyOpenApiTest.java
Fixes #753 
<details>
<summary>
</summary> …
> Add base-package available for custom config key

- .github/workflows/build.yml
- .github/workflows/build_website.yml
- .github/workflows/codeql.yml
Signed-off-by: Helber Belmiro <helber.belmiro@gmail.com>
(cherry picked from commit 72edb3f873e0478a463b50b7db9e7ad83a9be9a0)
> Added the `main-lts` branch to CI (#841)

- .github/project.yml
Merge this after LTS.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a …
> Release 2.7.0

- client/deployment/src/main/resources/templates/libraries/microprofile/api.qute
- client/integration-tests/path/pom.xml
- client/integration-tests/path/src/main/openapi/openapi-path-with-forward-slash.yaml
- client/integration-tests/path/src/main/openapi/openapi-path.yaml
- client/integration-tests/path/src/main/resources/application.properties
- client/integration-tests/path/src/test/java/io/quarkiverse/openapi/generator/it/PathTest.java
- client/integration-tests/pom.xml
> Fix path generate

- client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiConfigValidator.java
- client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java
- client/integration-tests/config-key/src/main/openapi/config-key-with-dash.yaml
- client/integration-tests/config-key/src/main/resources/application.properties
- client/integration-tests/config-key/src/test/java/io/quarkiverse/openapi/generator/configkey/QuarkusConfigKeyWithDashOpenApiTest.java
Fixes #778 
<details>
<summary>
</summary> …
> Support `-` on RegisterRestClient#configKey

- README.md
Converted to markdown blockers and remove the docs link duplication.
Maybe we should consider publishing docs for the latest released version?
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to …
> Small cleanup in README

- .github/project.yml
<details>
<summary>
</summary> …
> [2.4.x] Release 2.4.8

- .github/project.yml
<details>
<summary>
</summary> …
> [2.4.x] Release 2.4.8 (2nd try)

- .github/project.yml
<details>
<summary>
</summary> …
> release 2.8.1

- .github/project.yml
<details>
<summary>
</summary> …
> Relase 2.8.1-lts

- server/runtime/pom.xml
This pull request aims to add a description to server/runtime pom.xml. Actually on `code.quarkus.io` the server extension has the following description:
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) …
> Add description to server/runtime/pom.xml

- pom.xml
With the release o Quarkus 3.20.0 as the new LTS version, the quarkus version on the main-lts branch needs to be updated.
[Issue #1074 - Update LTS branch to quarkus 3.20 ](https://github.com/quarkiverse/quarkus-openapi-generator/issues/1074)
> [main-lts] Update quarkus version to 3.20.0

- client/deployment/src/main/resources/templates/libraries/microprofile/pojo.qute
- client/deployment/src/main/resources/templates/libraries/microprofile/pojoQueryParam.qute
Fix #1098: Rename key local variable to mapKey
> Fix #1098: Rename key local variable to mapKey

- client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/GeneratorProcessor.java
- client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/template/QuteTemplatingEngineAdapter.java
- client/oidc/src/main/java/io/quarkiverse/openapi/generator/oidc/providers/OAuth2AuthenticationProvider.java
- client/runtime/src/main/java/io/quarkiverse/openapi/generator/AuthenticationRecorder.java
- client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/AbstractAuthProvider.java
- client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/ApiKeyAuthenticationProvider.java
- client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/BasicAuthenticationProvider.java
- client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/BearerAuthenticationProvider.java
- client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/ConfigCredentialsProvider.java
- client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/CredentialsProvider.java
- client/runtime/src/test/java/io/quarkiverse/openapi/generator/providers/ApiKeyOpenApiSpecProviderTest.java
- client/runtime/src/test/java/io/quarkiverse/openapi/generator/providers/BearerOpenApiSpecProviderTest.java
- docs/modules/ROOT/pages/client.adoc
- docs/modules/ROOT/pages/includes/custom-auth-provider.adoc
Fix #1088.
<details>
<summary>
</summary> …
> Fix #1088 - Add support for custom credentials provider in runtime

- pom.xml
This PR reverts Quarkus version back to the LTS version.
The wrong version was set as part of https://github.com/quarkiverse/quarkus-openapi-generator/commit/dbc9f8f05bd49c3243ae118732e77c13e2e0f69e.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to …
> [main-lts] Fix Quarkus version

- pom.xml
<details>
<summary>
</summary> …
> [main-lts] Bumped Quarkus to 3.20.1

- client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/GeneratorProcessor.java
- client/integration-tests/generation-tests/pom.xml
Fixes #1151
<details>
<summary>
</summary> …
> Fix #1151 - Fail on scenarios where OAuth2 is required and OIDC is not in the classpath

- .github/workflows/build.yml
Cherry pick of https://github.com/quarkiverse/quarkus-openapi-generator/pull/1166.
> [main-lts] Reenable tests on Windows

- client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/ConfigCredentialsProvider.java
Fix https://github.com/quarkiverse/quarkus-openapi-generator/issues/1205
> [Fix #1205] Making easier inheriting from ConfigCredentialsProvider

- docs/modules/ROOT/pages/server.adoc
Closes #1051
<details>
<summary>
</summary> …
> Add documentation about Apicurio Codegen Extensions

- .github/project.yml
<details>
<summary>
</summary> …
> release 2.12.0

- docs/modules/ROOT/pages/server.adoc
Closes #1291
<details>
<summary>
</summary> …
> Solve type about x-codegen-type

- docs/modules/ROOT/pages/includes/quarkus-openapi-generator-moqu-wiremock.adoc
- docs/modules/ROOT/pages/includes/quarkus-openapi-generator-moqu-wiremock_quarkus.openapi-generator.adoc
- docs/modules/ROOT/pages/includes/quarkus-openapi-generator-server.adoc
- docs/modules/ROOT/pages/includes/quarkus-openapi-generator-server_quarkus.openapi.adoc
- server/deployment/src/main/java/io/quarkiverse/openapi/server/generator/deployment/CodegenConfig.java
<details>
<summary>
</summary> …
> Adjust JSR 303 property documentation
