README.md, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/SpecConfig.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/QuarkusJavaClientCodegen.java, deployment/src/main/resources/templates/api.qute, deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/SpecConfigTest.java, deployment/src/test/resources/circuitbreaker/application.properties, deployment/src/test/resources/circuitbreaker/circuit_breaker_disabled_application.properties, deployment/src/test/resources/circuitbreaker/missing_circuit_breaker_enabled_application.properties, deployment/src/test/resources/codegen/application.properties, integration-tests/example-project/src/main/resources/application.properties, integration-tests/example-project/src/test/java/io/quarkiverse/openapi/generator/it/OpenWeatherTest.java, integration-tests/example-project/src/test/java/io/quarkiverse/openapi/generator/it/WiremockOpenWeather.java, integration-tests/generation-tests/src/main/resources/application.properties, ˜!
In this PR, we changed the OpenAPI Spec file in the configuration keys to use underline (_) in place of (.). This is a breaking change, we will notify users in the release notes to change their configuration. With this change, users can set properties without the quotes, like:
```properties
quarkus.openapi-generator.codegen.spec.simple_openapi_json.base-package=org.acme.openapi.simple
```
For a file named `simple-openapi.json`. We follow the rules defined [here](https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configsources.asciidoc#environment-variables-mapping-rules) from Microprofile Configuration project. 
Additionally, now the `baseUri` and `configPrefix` attributes is defined in the generated `@RegisterRestClient` annotation. For example:
```java …
```
=> Standardize the openapi spec id in configs and add baseUri to the RegisterRestClient

deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java
The openApiNullable property controls the use of JsonNullable in the templates, and by consequence in generated classes. Since in this generator we are using our own templates that make no use of the JsonNullable wrapper but the property is not set, we are getting an extra import that is unused but breaks compilation if you don't have the needed dependency in your project. This commit fixes this by hardcoding this property to false.
This fixes the problem that originated https://github.com/quarkiverse/quarkus-openapi-generator/issues/66.
=> Add property to remove JsonNullable import

deployment/src/main/resources/templates/api.qute
PR to fix issue #86.
Adding @ApplicationScoped annotation to generated API will allow us to mock it in unit test according to official Quarkus guidelines https://quarkus.io/blog/mocking/#using-injectmock
=> Add @ApplicationScoped to generated api to allow mocking api for testing

README.md, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CodegenConfig.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/QuarkusJavaClientCodegen.java, deployment/src/main/resources/templates/auth/compositeAuthenticationProvider.qute, deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapperTest.java, integration-tests/example-project/src/main/openapi/open weather no security.yaml, integration-tests/example-project/src/main/resources/application.properties, integration-tests/example-project/src/test/java/io/quarkiverse/openapi/generator/it/OpenWeatherDefaultSecurityTest.java, integration-tests/example-project/src/test/java/io/quarkiverse/openapi/generator/it/WiremockOpenWeather.java
The idea of this enhancement is to provide a configuration option that allows users to enforce security for all endpoints, even if the specification file is not explicitly defining these via the `security` element. Example: Assuming we have a spec file that contains the `securitySchemes` definition, but no `security` reference:
```
securitySchemes:
basic_auth:
type: http
scheme: basic
```
With this enhancement, the generator will create authentication bindings if the following property is defined:
```
quarkus.openapi-generator.codegen.default.security.scheme=basic_auth
```
**Note:** The property value needs to match the name of the `securityScheme` in the spec file.
=> KOGITO-6458: Define default authentication method to be used by OpenAPI

deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CodegenConfig.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorJsonCodeGen.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorOutputPaths.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorStreamCodeGen.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorYamlCodeGen.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorYmlCodeGen.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/template/OpenApiNamespaceResolver.java, deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/CodegenConfigTest.java
For files generated from streams, relative spec file path rather than file name should be used for generating config key
=> Using full path as config key

deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/QuarkusJavaClientCodegen.java, deployment/src/main/resources/templates/api.qute, integration-tests/example-project/src/test/java/io/quarkiverse/openapi/generator/it/SimpleOpenApiTest.java
The goal of this PR is that if configuration is missing, the following message is printed
`Caused by: java.lang.IllegalArgumentException: Unable to determine the proper baseUrl/baseUri. Consider registering using @RegisterRestClient(baseUri="someuri"), @RegisterRestClient(configKey="orkey"), or by adding 'quarkus.rest-client."subtration_spec_yaml".url' or 'quarkus.rest-client."subtration_spec_yaml".uri' to your Quarkus configuration`
=> Do not put a default url if there is not server url

deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorStreamCodeGen.java
This PR fixes https://github.com/quarkiverse/quarkus-openapi-generator/issues/104.
=> Fixed possible NullPointerException in OpenApiGeneratorStreamCodeGen.java

deployment/src/main/resources/templates/api.qute, integration-tests/example-project/src/main/openapi/quarkus-simple-openapi.yaml, integration-tests/example-project/src/test/java/io/quarkiverse/openapi/generator/it/QuarkusSimpleOpenApiTest.java
This PR removes `import javax.ws.rs.core.Response;` from the api.qute template.
Maybe, as a follow up improvement, we should also [remove all imports from all the templates and qualify the classes on their usages](https://github.com/quarkiverse/quarkus-openapi-generator/issues/103).
WDYT @ricardozanini?
=> Removed import that might cause compilation error due to ambiguity

deployment/src/main/resources/templates/api.qute, deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapperTest.java, deployment/src/test/resources/openapi/simple-openapi.json
The generated annotation `@GeneratedMethod` currently uses as a value a sanitized name for the `operationId`. This is necessary for codegen because it is/can be used as java identifier, for instance, in method, variable or class name.  The issue with that, is that the reference to the operationId is lost. For example, an operationId of `Jobs doJob` gets translated to `jobsDoJob`, in a method with the same name. In the case of the annotation value, it makes sense that we keep the original String, because is not used for the codegen, it is a simple string. By using the original operationId, without sanitizing, it allows consumer applications to track back with an exact match to the `operationId` contained in the OpenAPI spec file.
=> Use original operationId in annotated GeneratedMethod

README.md, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/ClassCodegenConfigParser.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/ModelCodegenConfigParser.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/template/OpenApiNamespaceResolver.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java, deployment/src/main/resources/templates/api.qute, deployment/src/main/resources/templates/model.qute, deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapperTest.java, deployment/src/test/resources/deprecated/application.properties, deployment/src/test/resources/openapi/deprecated.json
OK this IF will skip generating the operation if its deprecated. 
```
{#if !op.deprecated || openapi:genDeprecatedApiAttr(package, classname, codegen)}
```
=> Fix #135: Exclude deprecated operations

README.md, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CodegenConfig.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/SpecItemConfig.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java, deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapperTest.java, integration-tests/example-project/src/main/openapi/type-mappings-testing.yml, integration-tests/example-project/src/main/resources/application.properties, integration-tests/example-project/src/test/java/io/quarkiverse/openapi/generator/it/TypeAndImportMappingTest.java, integration-tests/example-project/src/test/java/io/quarkiverse/openapi/generator/it/WiremockTypeAndImportMapping.java
This PR will enable users to configure their own type mappings via the properties. For example, this allows users to use `InputStream` for their multipart file uploads (instead of the default `File`) as request in #118 .
NB: still a work in progress
=> Adding typemapping option to the generator

deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/SpecItemConfig.java
As mentioned by @melloware in https://github.com/quarkiverse/quarkus-openapi-generator/issues/118#issuecomment-1286139685 Quarkus will generate unnecessary warnings when setting the `type-mappings` and `import-mappings` configuration items. For example setting this:
```
quarkus.openapi-generator.codegen.spec.documents_openapi_yml.type-mappings.File=InputStream
quarkus.openapi-generator.codegen.spec.documents_openapi_yml.import-mappings.File=java.io.InputStream
```
would cause the following warnings during code generation
```
[WARNING] [io.quarkus.config] Unrecognized configuration key "quarkus.openapi-generator.codegen.spec.documents_openapi_yml.type-mappings.File" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make …
```
=> Removing unnecessary Optional in SpecItemConfig for type and import mappings

README.md, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/QuarkusJavaClientCodegen.java, deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapperTest.java, deployment/src/test/resources/openapi/datetime-regression.yml
This removes the default datelibrary `java8` and replaces it with the appropriate type and import mappings. The standard behaviour for the OAS `date` and `DateTime` types should not be changed. But now users can also override these mappings, for example:
```
type-mappings:
"date" -> "ThaiBuddhistDate"
"DateTime" -> "Instant"
import-mappings:
"ThaiBuddhistDate" -> "java.time.chrono.ThaiBuddhistDate"
"Instant" -> "java.time.Instant"
```
=> Enabling custom data and datetime mappings

deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java, integration-tests/ignore/src/test/java/io/quarkiverse/openapi/generator/it/IgnoreTest.java, pom.xml
Bumps `quarkus.version` from 2.14.1.Final to 2.14.2.Final.
Updates `quarkus-bom` from 2.14.1.Final to 2.14.2.Final
- [Release notes](https://github.com/quarkusio/quarkus/releases)
- [Commits](https://github.com/quarkusio/quarkus/compare/2.14.1.Final...2.14.2.Final)
Updates `quarkus-maven-plugin` from 2.14.1.Final to 2.14.2.Final
Updates `quarkus-bootstrap-maven-plugin` from 2.14.1.Final to 2.14.2.Final
---
- dependency-name: io.quarkus:quarkus-bom dependency-type: direct:production update-type: version-update:semver-patch
- dependency-name: io.quarkus:quarkus-maven-plugin dependency-type: direct:production update-type: version-update:semver-patch
- dependency-name: io.quarkus:quarkus-bootstrap-maven-plugin dependency-type: direct:production update-type: …
=> Bump quarkus.version from 2.14.1.Final to 2.14.2.Final (#186)

deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java
Fixing issue #196 
An exception was being thrown when trying to substring a path not including 'src' in it. Now it's controlled that the index for the substring is valid before doing it.
=> Control when path has not 'src' in it

.github/dependabot.yml
Fixes: https://github.com/quarkiverse/quarkus-openapi-generator/issues/209
=> Added quarkus2 branch to dependabot.yml

deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/SpecItemConfig.java
Signed-off-by: Helber Belmiro <helber.belmiro@gmail.com>
Backport of https://github.com/quarkiverse/quarkus-openapi-generator/pull/221
=> Fixed issue that prevented the app from starting when "base-package" property was not set (#221)

README.md, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CodegenConfig.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/SpecItemConfig.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java, deployment/src/main/resources/templates/api.qute, integration-tests/pom.xml, integration-tests/return-response/pom.xml, integration-tests/return-response/src/main/openapi/model-simple-openapi.yaml, integration-tests/return-response/src/main/openapi/response-simple-openapi.yaml, integration-tests/return-response/src/main/resources/application.properties, integration-tests/return-response/src/test/java/io/quarkiverse/openapi/generator/it/ReturnResponseTest.java
Fixes: https://github.com/quarkiverse/quarkus-openapi-generator/issues/174
I named the property `return-response` since `interfaceOnly` doesn't describe this feature and might confuse users. I'm also open to better property names.
=> Added "return-response" property to return `Response` instead of a model

.github/dependabot.yml
Fixes: https://github.com/quarkiverse/quarkus-openapi-generator/issues/227
=> Dependabot configuration changed to act only on main branch

.github/dependabot.yml
Backport of: https://github.com/quarkiverse/quarkus-openapi-generator/pull/228
=> Dependabot configuration changed to act only on main branch (#228)

README.md
Small change to our docs to reflect a suggestion to look for Apicurio in case one needs to generate code for the server-side.
=> Add Apicurio reference in the README

pom.xml
Backport of https://github.com/quarkiverse/quarkus-openapi-generator/pull/229
=> Bump assertj-core from 3.23.1 to 3.24.1 (#229)

pom.xml
Backport of https://github.com/quarkiverse/quarkus-openapi-generator/pull/230
=> Bump javaparser-core from 3.24.9 to 3.24.10 (#230)

pom.xml
Backport of: https://github.com/quarkiverse/quarkus-openapi-generator/pull/240
Bumps assertj-core from 3.24.1 to 3.24.2.
---
- dependency-name: org.assertj:assertj-core dependency-type: direct:production update-type: version-update:semver-patch ...
Signed-off-by: dependabot[bot] <support@github.com>
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
=> Bump assertj-core from 3.24.1 to 3.24.2 (#240)

runtime/pom.xml
This is necessary to display the proper description in the tooling
=> Add missing description

deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/template/QuteTemplatingEngineAdapter.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/QuarkusJavaClientCodegen.java, deployment/src/main/resources/templates/auth/compositeAuthenticationProvider.qute, runtime/src/main/java/io/quarkiverse/openapi/generator/providers/AbstractAuthProvider.java, runtime/src/main/java/io/quarkiverse/openapi/generator/providers/ApiKeyAuthenticationProvider.java, runtime/src/main/java/io/quarkiverse/openapi/generator/providers/BasicAuthenticationProvider.java, runtime/src/main/java/io/quarkiverse/openapi/generator/providers/BearerAuthenticationProvider.java, runtime/src/main/java/io/quarkiverse/openapi/generator/providers/OAuth2AuthenticationProvider.java
Fixes: https://github.com/quarkiverse/quarkus-openapi-generator/issues/242
There's a tiny piece of code that still needs to be generated because of `clientId`: https://github.com/quarkiverse/quarkus-openapi-generator/pull/248/files#diff-1fa4a5b1488fae8e12f5730d80671494aee2bdff745d5f13df3911575b84a7b5R199-R210
=> Changed oauth2AuthenticationProvider.qute to not be generated

pom.xml
Backport of: https://github.com/quarkiverse/quarkus-openapi-generator/pull/264
Bumps [javaparser-core](https://github.com/javaparser/javaparser) from 3.25.0 to 3.25.1.
- [Release notes](https://github.com/javaparser/javaparser/releases)
- [Changelog](https://github.com/javaparser/javaparser/blob/master/changelog.md)
- [Commits](https://github.com/javaparser/javaparser/compare/javaparser-parent-3.25.0...javaparser-parent-3.25.1)
---
- dependency-name: com.github.javaparser:javaparser-core dependency-type: direct:production update-type: version-update:semver-patch ...
=> Bump javaparser-core from 3.25.0 to 3.25.1 (#264)

deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/template/QuteTemplatingEngineAdapterTest.java
@hbelmiro please find attached my PR for issue https://github.com/quarkiverse/quarkus-openapi-generator/issues/267
=> fixes: getResource puts a leading slash before the disk name on Windows

deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/template/QuteTemplatingEngineAdapterTest.java
Backport of https://github.com/quarkiverse/quarkus-openapi-generator/pull/268
=> getResource puts a leading slash before the disk name on Windows (#268)

deployment/src/main/resources/templates/auth/compositeAuthenticationProvider.qute, runtime/src/main/java/io/quarkiverse/openapi/generator/providers/OAuth2AuthenticationProvider.java
Fixes: https://github.com/quarkiverse/quarkus-openapi-generator/issues/272
=> Replaced `io.quarkus.arc.Priority` with `jakarta.annotation.Priority`

.github/dependabot.yml, .github/workflows/build.yml, .github/workflows/quarkus-snapshot.yaml, .github/workflows/release.yml
Fixes the following GitHub Action warnings:
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-java@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-command …
```
=> fix: Several GitHub actions are outdated

deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java
My upstream contribution has been merged https://github.com/quarkusio/quarkus/pull/31769, thus we can align the capability detection logic. 
However, I'm not sure whether we should backport this to ``quarkus2``, cause it requires at least Quarkus ``2.16.5.Final``.
@hbelmiro WDYT?
=> fix: Alignment of the capability detection logic

pom.xml
Backport of: https://github.com/quarkiverse/quarkus-openapi-generator/pull/292
=> Bump [javaparser-core](https://github.com/javaparser/javaparser) from 3.25.1 to 3.25.2

runtime/pom.xml
Backport of https://github.com/quarkiverse/quarkus-openapi-generator/pull/299
=> Replaced quarkus-bootstrap-maven-plugin with quarkus-extension-maven-plugin

pom.xml
Cherry-pick of https://github.com/quarkiverse/quarkus-openapi-generator/pull/305
Bumps [quarkiverse-parent](https://github.com/quarkiverse/quarkiverse-parent) from 12 to 13.
- [Release notes](https://github.com/quarkiverse/quarkiverse-parent/releases)
- [Commits](https://github.com/quarkiverse/quarkiverse-parent/commits)
---
- dependency-name: io.quarkiverse:quarkiverse-parent dependency-type: direct:production update-type: version-update:semver-major ...
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
(cherry picked from commit 6366db103c0cd3b999ea03e2de76cb4790c86a4c)
=> Bump quarkiverse-parent from 12 to 13 (#305)

deployment/pom.xml
Cherry-pick of https://github.com/quarkiverse/quarkus-openapi-generator/pull/307
Bumps [slf4j-ext](https://github.com/qos-ch/slf4j) from 2.0.3 to 2.0.7.
- [Release notes](https://github.com/qos-ch/slf4j/releases)
- [Commits](https://github.com/qos-ch/slf4j/compare/v_2.0.3...v_2.0.7)
---
- dependency-name: org.slf4j:slf4j-ext dependency-type: direct:production update-type: version-update:semver-patch ...
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
(cherry picked from commit c47795fff3193b7fd02f68c82a1675c07d72ebee)
=> Bump slf4j-ext from 2.0.3 to 2.0.7 (#307)

integration-tests/security/src/main/openapi/fooopenapi.json, integration-tests/security/src/main/resources/application.properties, integration-tests/security/src/test/java/io/quarkiverse/openapi/generator/it/security/AuthorizationHeaderApiKeyCanFilterWithoutDuplicateAuthorizationTest.java, integration-tests/security/src/test/java/io/quarkiverse/openapi/generator/it/security/WiremockFoo.java, runtime/src/main/java/io/quarkiverse/openapi/generator/providers/ApiKeyAuthenticationProvider.java
Cherry-pick of: https://github.com/quarkiverse/quarkus-openapi-generator/pull/311
* #308 do not duplicate Authorization header, see https://github.com/quarkiverse/quarkus-openapi-generator/issues/308
* #308 add IT test
* #308 linter
* #308 use LoggedRequest case. remove comments.
* #308 count the Authorization headers
* #308 log if api-key is empty
* #308 fix isEmpty
---------
Co-authored-by: Laurent Perez <laurent.perez@itk.fr>
(cherry picked from commit dfedbabf3716ea6a906566c41840b38bce9e2b2e)
=> #308 do not duplicate Authorization header, see https://github.com/quarkiverse/quarkus-openapi-generator/issues/308

deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java
Fixes: https://github.com/quarkiverse/quarkus-openapi-generator/issues/343
=> Changed to io.quarkiverse.openapi.generator.deployment.codegen.OpenApiGeneratorCodeGenBase.shouldRun return false instead of throwing exception

deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java
Cherry-pick of: https://github.com/quarkiverse/quarkus-openapi-generator/pull/346
=> Changed to io.quarkiverse.openapi.generator.deployment.codegen.OpenApiGeneratorCodeGenBase.shouldRun return false instead of throwing exception (#346)

integration-tests/security/src/main/resources/application.properties, integration-tests/security/src/test/java/io/quarkiverse/openapi/generator/it/security/AuthorizationHeaderApiKeyCanFilterWithoutDuplicateAuthorizationTest.java, runtime/src/main/java/io/quarkiverse/openapi/generator/providers/ApiKeyAuthenticationProvider.java
Co-authored-by: Laurent Perez <laurent.perez@itk.fr>
(cherry picked from commit 432a8a0f339f20d6e5d59746fabf75e844f9dba6)
=> #352 enable api key override for Authorization header (#355)

README.md, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CodegenConfig.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/SpecItemConfig.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/QuarkusJavaClientCodegen.java, deployment/src/main/resources/templates/api.qute, integration-tests/security/src/main/openapi/open weather v3.yaml, integration-tests/security/src/main/openapi/open weather v4.yaml, integration-tests/security/src/main/resources/application.properties, integration-tests/security/src/test/java/io/quarkiverse/openapi/generator/it/security/OpenWeatherTest.java
New option to define ClientHeadersFactory class for @RegisterClientHeaders
Example: quarkus.openapi-generator.codegen.spec.my_openapi_yaml.client-header-factory=org.DummyClientHeadersFactory
Be default AuthenticationPropagationHeadersFactory class is used.
If 'client-header-factory' is set to 'none', @RegisterClientHeaders will be set without any ClientHeadersFactory and default DefaultClientHeadersFactoryImpl will be used.
Related issue: https://github.com/quarkiverse/quarkus-openapi-generator/issues/290
=> client-headers-factory option

integration-tests/circuit-breaker/src/test/java/io/quarkiverse/openapi/generator/it/circuit/breaker/SimpleOpenApiTest.java
The test was comparing equality between `String` and `SimpleName` objects.
=> Fixed assertNotEquals with different types

integration-tests/security/pom.xml, integration-tests/security/src/main/java/io/quarkiverse/openapi/generator/it/security/TokenPropagationResource.java, integration-tests/security/src/main/openapi/token-propagation-external-service1.yaml, integration-tests/security/src/main/openapi/token-propagation-external-service2.yaml, integration-tests/security/src/main/openapi/token-propagation-external-service3.yaml, integration-tests/security/src/main/openapi/token-propagation-external-service4.yaml, integration-tests/security/src/main/openapi/token-propagation-external-service5.yaml, integration-tests/security/src/main/resources/application.properties, integration-tests/security/src/test/java/io/quarkiverse/openapi/generator/it/security/KeycloakServiceMock.java, integration-tests/security/src/test/java/io/quarkiverse/openapi/generator/it/security/TokenPropagationExternalServicesMock.java, integration-tests/security/src/test/java/io/quarkiverse/openapi/generator/it/security/TokenPropagationTest.java
Tests enabled only for RESTEasy Classic due to https://github.com/quarkiverse/quarkus-openapi-generator/issues/434
=> Added tests for token propagation

README.md
Backport of https://github.com/quarkiverse/quarkus-openapi-generator/pull/470
=> docs: fix documentation (#470)

deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/QuarkusJavaClientCodegen.java
Workaround for https://github.com/OpenAPITools/openapi-generator/issues/16531
Fixes remaining compilation problems for https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/ghes-3.10/ghes-3.10.json in https://github.com/quarkiverse/quarkus-openapi-generator/issues/460
=> Enhace special characters replacement

deployment/pom.xml, deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java
This PR fixes https://github.com/quarkiverse/quarkus-openapi-generator/issues/499
Some thoughts on this PR:
- I'm wasn't able to write some automated tests. That's because the test setup would be quite complex. We would need to compile the extension with Quarkus ``4.3.1`` and would test the extension with a business app using Quarkus in a previous 3.X version. Anyhow, I was able to test the functionality manually. Up to you if this would be good enough to continue. Otherwise somebody else is most welcome to write such a test.
- This code can be reverted as soon as we drop support for Quarkus versions earlier than ``3.4.1`` 
- I did some further testing and it looks like ``quarkus-openapi-generator`` in version ``2.2.10`` does also not support the Quarkus LTS branch (e.g. ``3.2.5.Final``). …
=> Determine REST_CLIENT_REACTIVE_JACKSON capability properly

deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/QuarkusJavaClientCodegen.java, deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/wrapper/QuarkusJavaClientCodegenTest.java
Fixes https://github.com/quarkiverse/quarkus-openapi-generator/issues/537
Fixes https://github.com/quarkiverse/quarkus-openapi-generator/issues/421
I'm sorry for the issue.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch …
=> Fixes wrong behavior with right enum name

runtime/src/main/java/io/quarkiverse/openapi/generator/providers/UrlPatternMatcher.java, runtime/src/test/java/io/quarkiverse/openapi/generator/providers/UrlPatternMatcherTest.java
Fixes: #555 
The UrlPatternMatcher is not matching URLs with path parameters containing the "-" character.
The following error is throw when using such URL:
```
java.util.regex.PatternSyntaxException: Illegal repetition near index 7
/pets/{pet-id}/types/{type-id}(?:\?.*?)?$
```
The root cause is the following pattern: `private static final String URL_PARAM_REGEX = "\\{(\\w*?)\\}";`. 
Here the `\w` is not considering the "-" character as part of a word thus not matching.
The "-" being an authorized character in the URL parameter, the pattern used shall match.
By using `\S` instead, the pattern is matching the parameters as expected.
---
<details>
<summary>
</summary>
In …
=> Fix UrlPatternMatcher not matching parameters in path containing "-" character

runtime/src/main/java/io/quarkiverse/openapi/generator/providers/BearerAuthenticationProvider.java
Request for `BearerAuthenticationProvider` not to add a blank token to the `Authorization` header, as doing so will never satisfy any real authorization requirement, and may cause a request failure when multiple `Authorization` headers are sent due to multiple (optional) `security` schemes are defined on an endpoint.
This change could be extended to the other `AuthProvider`s, but I have not been using those.
Fixes: #589
=> Do not add blank Bearer token

.github/workflows/build.yml, .github/workflows/build_website.yml, .github/workflows/preview.yml
This pull request aims to fix the issue #599.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it …
=> Try to fix upload-artifact@v4 issue

docs/modules/ROOT/pages/includes/getting-started.adoc, docs/modules/ROOT/pages/includes/logging.adoc
<details>
<summary>
</summary> …
=> [Main] Clarify vague points in documentation

CONTRIBUTING.md, README.md, docs/modules/ROOT/pages/includes/getting-started.adoc, docs/modules/ROOT/pages/index.adoc
This PR updates the docs to drop support for Quarkus2.
@ricardozanini can you please archive `quarkus2` branch? I don't have permission.
=> Dropped support for Quarkus 2

.github/workflows/build.yml, .github/workflows/codeql.yml, .github/workflows/release.yml, .lgtm.yml, README.md, pom.xml
Fixes: https://github.com/quarkiverse/quarkus-openapi-generator/issues/639
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a …
=> Added support for Java 21 and removed support for Java 11

deployment/src/main/resources/templates/libraries/microprofile/pojo.qute, integration-tests/array-enum/src/main/openapi/array-enum.yaml, integration-tests/array-enum/src/test/java/io/quarkiverse/openapi/generator/it/ArrayEnumTest.java
When in the model there is a field, that is for example a list and is not diffined as requierd in the yaml, then in the add method there is no initialization, if this field is null.
Fix it as openapi does it, in each "add" method for a container, generate a check if the container is null, if it's null instantiate a new empty container. 
@ricardozanini 
Is there an option to backport this to 2.2.16? Or should we do this local in our Nexus?
=> [issue: #651] Adding initialization for non requiered containers in add/put method

.github/project.yml
Release to include #635 required by the community. See the discussion here #625.
=> Prepare for release 2.4.0

docs/modules/ROOT/pages/includes/server-getting-started.adoc, docs/modules/ROOT/pages/server.adoc
Fixes #686
<details>
<summary>
</summary> …
=> Fix getting started server documentation

client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CodegenConfig.java, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CommonItemConfig.java, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/template/QuteTemplatingEngineAdapter.java, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java, client/deployment/src/main/resources/templates/libraries/microprofile/additionalEnumTypeUnexpectedMember.qute, client/deployment/src/main/resources/templates/libraries/microprofile/enumClass.qute, client/deployment/src/main/resources/templates/libraries/microprofile/enumOuterClass.qute, client/integration-tests/enum-unexpected/pom.xml, client/integration-tests/enum-unexpected/src/main/openapi/with-enum-unexpected.yaml, client/integration-tests/enum-unexpected/src/main/openapi/without-enum-unexpected.yaml, client/integration-tests/enum-unexpected/src/main/resources/application.properties, client/integration-tests/enum-unexpected/src/test/java/io/quarkiverse/openapi/generator/it/EnumUnexpectedTest.java, client/integration-tests/pom.xml, docs/modules/ROOT/pages/client.adoc, docs/modules/ROOT/pages/includes/supporting-unexpected-enums-values.adoc
resolves quarkiverse/quarkus-openapi-generator#692
This is a first draft, I would follow the guidelines if you thinks this feature is useful.
I still have an issue with numbered enum that I need to dig into, but I'd like to have a first feedback on this version.
=> First draft to support unexpected enum values

client/deployment/src/main/resources/templates/libraries/microprofile/enumClass.qute, client/integration-tests/enum-property/src/main/openapi/enum-property.yaml, client/integration-tests/enum-property/src/test/java/io/quarkiverse/openapi/generator/it/EnumPropertyTest.java
a fix for issue #715. It works and test passes, but please check my small changes as I didn't work with Qute before and maybe there is a better solution
=> BigDecimal value fix in enums (#715)

.github/ISSUE_TEMPLATE/-issue-number---problem-description-.md
---
Updated the issue template to improve issue categorization and handling by adding specific fields and clarifications. This update ensures that all necessary information is captured right at the start, aiding in more efficient issue resolution.
Fixes #677
=> [main] Updated issues template

client/deployment/pom.xml, client/runtime/pom.xml, pom.xml, server/deployment/pom.xml, server/runtime/pom.xml
I created an issue #793, to use `@ConfigMapping`. This pull request just solves the build. 
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still …
=> Config quarkus-extension-processor to use legacy @ConfigRoot

client/deployment/src/main/resources/templates/libraries/microprofile/pojo.qute, client/integration-tests/bean-validation/src/main/openapi/bean-validation-true.yaml, client/integration-tests/bean-validation/src/test/java/io/quarkiverse/openapi/generator/it/BeanValidationTest.java
Following changes concern generating POJOs using client with `use-bean-validation` property set to `true`.
There is a functionality of annotating required fields with Jakarta @NotNull. According to my tests, it does not work in case when the field has no other constraints (like minLength, maxLength, etc.). I expect that required fields are annotated with NotNull no matter it has any other constraints or not.
I would suggest a little modification in pojo.qute in order to annotate every required field.
=> Adding NotNull annotation for required fields

client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/OpenApiGeneratorOptions.java, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorStreamCodeGen.java, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/QuarkusJavaClientCodegen.java, client/deployment/src/main/resources/templates/libraries/microprofile/api.qute, client/deployment/src/main/resources/templates/libraries/microprofile/model.qute
Closes #819
Closes #796
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a …
=> Set use-bean-validation false as default

client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/QuarkusJavaClientCodegen.java, client/deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapperTest.java, client/deployment/src/test/resources/openapi/issue-flink.yaml
In this PR, we add a WARN to the logs when the OpenAPI file has duplicated element variables. For example:
```yaml
CheckpointInfo:
type: object
properties:
checkpointId:
type: integer
format: int64
failureCause:
$ref: '#/components/schemas/SerializedThrowable'
SavepointInfo:
type: object
properties:
failure-cause:
$ref: '#/components/schemas/SerializedThrowable'
location:
type: string
```
Will fail because `failure-cause` and `failureCause` are the same variables from the Java syntax perspective as soon as we convert both to CamelCase.
**Why not remove the duplicates?**
Because users will only realize this bug in runtime when it's too late, and Json marshaling won't work: …
=> No Issue - Add a warn in the logs when elements have duplicated vars

client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiConfigValidator.java
This PR fixes a warning that complains about using the old Stream API. It changes to use `java.util.stream.Stream#toList`.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. …
=> Fixed warning

client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/GeneratorProcessor.java, client/integration-tests/pom.xml, client/integration-tests/without-oidc/pom.xml, client/integration-tests/without-oidc/src/main/openapi/quarkus-simple-openapi.yaml, client/integration-tests/without-oidc/src/main/resources/application.properties, client/integration-tests/without-oidc/src/test/java/io/quarkiverse/openapi/generator/it/QuarkusSimpleOpenApiTest.java
Fix #824 
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or …
=> Fix Build fails if quarkus-oidc-client is not in the classpath

client/deployment/src/main/resources/templates/libraries/microprofile/auth/compositeAuthenticationProvider.qute, client/deployment/src/main/resources/templates/libraries/microprofile/auth/headersFactory.qute
As otherwise using the `configKey` instead can lead to a mismatch and an exception like:
```
[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.quarkiverse.openapi.generator.providers.CompositeAuthenticationProvider and qualifiers [@OpenApiSpec(openApiSpecId = "your-config-key-not-the-same-as-spec-id")]
- injection target: parameter 'compositeProvider' of com.acme.api.auth.AuthenticationPropagationHeadersFactory constructor
- declared on CLASS bean [types=[com.acme.api.auth.AuthenticationPropagationHeadersFactory, io.quarkiverse.openapi.generator.providers.AbstractAuthenticationPropagationHeadersFactory, …
```
=> Consistently use `quarkus-generator.openApiSpecId` as openApiSpecId in templates

client/runtime/src/main/resources/META-INF/quarkus-extension.yaml
Add missing link for the guide to the extensions page.
https://quarkus.io/extensions/io.quarkiverse.openapi.generator/quarkus-openapi-generator/
=> Link to extension guide on the extensions site

client/deployment/pom.xml, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/GeneratorProcessor.java, client/deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/authentication/OpenApiSpecProviderTest.java, client/integration-tests/enum-unexpected/pom.xml, client/integration-tests/polymorphism/pom.xml, client/integration-tests/pom.xml, client/integration-tests/security/pom.xml, client/integration-tests/security/src/test/java/io/quarkiverse/openapi/generator/it/security/TokenPropagationExternalServicesMock.java, client/integration-tests/without-oidc/pom.xml, client/integration-tests/without-oidc/src/main/resources/application.properties, client/oidc/pom.xml, client/oidc/src/main/java/io/quarkiverse/openapi/generator/oidc/ClassicOidcClientRequestFilterDelegate.java, client/oidc/src/main/java/io/quarkiverse/openapi/generator/oidc/OidcAuthenticationRecorder.java, client/oidc/src/main/java/io/quarkiverse/openapi/generator/oidc/ReactiveOidcClientRequestFilterDelegate.java, client/oidc/src/main/java/io/quarkiverse/openapi/generator/oidc/providers/OAuth2AuthenticationProvider.java, client/pom.xml, client/runtime/pom.xml, client/runtime/src/main/java/io/quarkiverse/openapi/generator/AuthConfig.java, client/runtime/src/main/java/io/quarkiverse/openapi/generator/AuthenticationRecorder.java, client/runtime/src/test/java/io/quarkiverse/openapi/generator/providers/AbstractOpenApiSpecProviderTest.java, docs/modules/ROOT/pages/includes/authentication-support.adoc
Fix #824 
In this PR:
- Removed references of OIDC libraries from the main `runtime` module
- I created a separate `quarkus-openapi-generator-oidc` component to hold OIDC use cases; users now MUST add this new dependency to their project in case OIDC is required.
- Review the `integration-tests` module to remove OIDC from every module; just add to `security` where it's really required.
- Updated documentation.
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name …
=> Fix #824 - Introduce a separated OIDC module to hold security dependencies

client/integration-tests/beanparam/pom.xml, client/integration-tests/change-custom-template-directory/pom.xml, client/integration-tests/change-directory/pom.xml, client/integration-tests/cookie-authentication/pom.xml, client/integration-tests/enum-property/pom.xml, client/integration-tests/enum-property/src/test/java/io/quarkiverse/openapi/generator/it/EnumPropertyTest.java, client/integration-tests/enum-unexpected/pom.xml, client/integration-tests/enum-unexpected/src/test/java/io/quarkiverse/openapi/generator/it/EnumUnexpectedTest.java, client/integration-tests/generation-tests/pom.xml, client/integration-tests/multipart-request/pom.xml, client/integration-tests/open-api-normalizer/pom.xml, client/integration-tests/polymorphism/pom.xml, client/integration-tests/polymorphism/src/test/java/io/quarkiverse/openapi/generator/it/PolymorphismTest.java, client/integration-tests/pom.xml, client/integration-tests/security/pom.xml, client/integration-tests/skip-validation/pom.xml, client/integration-tests/type-mapping/pom.xml, client/test-utils/pom.xml, pom.xml
In this PR:
- Upgrade WireMock to `3.9.2` and change group and artifact IDs
- Add Jboss RestEasy Multipart to the `integration-tests` module since on [Quarkus 3.15.x](https://github.com/quarkusio/quarkus/blob/3.15/extensions/resteasy-classic/resteasy-client/runtime/pom.xml), this dependency is not added to RestEasy Client.
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-quarkus2` to …
=> NO-ISSUE: Upgrade WireMock to `3.9.2`; Add Jboss RestEasy Multipart to IT

client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CodegenConfig.java, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/SpecItemConfig.java, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java, client/integration-tests/remove-operationid-prefix/src/main/openapi/openapi-prefix-count.yaml, client/integration-tests/remove-operationid-prefix/src/main/openapi/openapi-prefix-delimiter.yaml, client/integration-tests/remove-operationid-prefix/src/main/resources/application.properties, client/integration-tests/remove-operationid-prefix/src/test/java/io/quarkiverse/openapi/generator/it/RemoveOperationIdPrefixTest.java, docs/modules/ROOT/pages/includes/getting-started.adoc
=> Improve remove operation id prefix

client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CodegenConfig.java, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CommonItemConfig.java, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java, client/deployment/src/main/resources/templates/libraries/microprofile/pojo.qute, client/integration-tests/equals-hashcode/pom.xml, client/integration-tests/equals-hashcode/src/main/openapi/quarkus-equals-hashcode-openapi.yaml, client/integration-tests/equals-hashcode/src/main/openapi/quarkus-non-equals-hashcode-openapi.yaml, client/integration-tests/equals-hashcode/src/main/resources/application.properties, client/integration-tests/equals-hashcode/src/test/java/io/quarkiverse/openapi/generator/it/EqualsHashcodeTest.java, client/integration-tests/equals-hashcode/src/test/java/io/quarkiverse/openapi/generator/it/VerifyGenerationTest.java, client/integration-tests/pom.xml, docs/modules/ROOT/pages/client.adoc, docs/modules/ROOT/pages/includes/equals-hashcode.adoc
I have added so `equals` and `hashCode` is generated to the models. It's possible to disabled it if someone doesn't want it.
@ricardozanini I created an new branch and pull request, it was easier and faster for me to do that.
The result looks like this:
```
@Override
public boolean equals(Object o) {
if (this == o) return true;
if (o == null || getClass() != o.getClass()) return false;
Animal model = (Animal) o;
return Objects.equals(born, model.born) &&
Objects.equals(deceased, model.deceased);
}
@Override
public int hashCode() {
return Objects.hash(born,
deceased);
}
```
=> Added so equals and hashcode is generated in models.

client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/template/OpenApiNamespaceResolver.java, client/deployment/src/main/resources/templates/libraries/microprofile/auth/compositeAuthenticationProvider.qute, client/deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapperTest.java, client/deployment/src/test/resources/openapi/issue-933-security.yaml
Closes #933 
In this PR, we added a new custom Qute template function to filter OAuth methods by name since only one `CompositeAuthenticationProvider` class is required to process OIDC authentication per OAuth instance.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to …
=> Fix #933 - Filter oauth security definitions from spec when generating `CompositeAuthenticationProvider`

server/deployment/src/main/java/io/quarkiverse/openapi/server/generator/deployment/codegen/ApicurioOpenApiServerCodegen.java, server/deployment/src/test/java/io/quarkiverse/openapi/server/generator/deployment/CodegenTest.java, server/deployment/src/test/resources/io/quarkiverse/openapi/server/generator/deployment/doesNotExistDir.application.properties
Fixes #871 
I am not sure if this pull request solves the issue, but I think that shows a better message.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring …
=> Add validation when the input-base-dir is not present

client/deployment/pom.xml, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CodegenConfig.java, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CommonItemConfig.java, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/GlobalCodegenConfig.java, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/SpecItemConfig.java, client/runtime/pom.xml, client/runtime/src/main/java/io/quarkiverse/openapi/generator/AuthsConfig.java, client/runtime/src/main/java/io/quarkiverse/openapi/generator/OpenApiGeneratorConfig.java, client/runtime/src/main/java/io/quarkiverse/openapi/generator/SpecItemConfig.java, server/deployment/pom.xml, server/deployment/src/main/java/io/quarkiverse/openapi/server/generator/deployment/CodegenConfig.java
Fixes #https://github.com/quarkiverse/quarkus-openapi-generator/issues/793
This pull request convert the extension to use the new way to configure a extension. This pull request follows the migration guide, removing the need to use the following option:
```xml
<compilerArgs><arg>-AlegacyConfigRoot=true</arg>
```
Additionaly, I change the security configuration to be RUNTIME phase.
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull …
=> Convert client and server modules to use @ConfigMapping

client/deployment/src/main/resources/templates/libraries/microprofile/api.qute, client/integration-tests/change-custom-template-directory/src/main/custom/templates/api.qute, client/integration-tests/custom-templates/src/main/resources/templates/api.qute
Fixes https://github.com/quarkiverse/quarkus-openapi-generator/issues/959
This PR fixes a condition in the `api.qute` template that was making the generated Api.java not include the `baseUri` even if it was present in openapi spec file.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an …
=> [issues#959] Fix `api.qute` condition to include the `baseUri` to `@RegisterRestClient`

client/deployment/src/main/resources/templates/libraries/microprofile/beanValidationCore.qute, client/integration-tests/bean-validation/src/test/java/io/quarkiverse/openapi/generator/it/BeanValidationTest.java
Fixed #964 
This PR fixes a condition in the `beanValidationCore.qute` template that was making the generated model classes fields not include the jakarta.validation.Valid annotation when `use-bean-validation` was `true`.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to …
=> [issues#964] Fix beanValidationCore.qute condition to include the jakarta.validation.Valid annotation

server/runtime/pom.xml
(I'm currently going through the Quarkiverse extensions using legacy config roots).
=> Drop legacyConfigRoot as it is not necessary

client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/UrlPatternMatcher.java, client/runtime/src/test/java/io/quarkiverse/openapi/generator/providers/UrlPatternMatcherTest.java
Fix https://github.com/quarkiverse/quarkus-openapi-generator/issues/991
=> [Fix #991] Changing URLPatternMatcher implementation

client/deployment/src/main/resources/templates/libraries/microprofile/pojo.qute
Fix #1029 
`toString()` was ignoring these fields but not `equals()/hashcode()`
=> Fix #1029: POJO ignore deprecated in hashcode/equals

client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/GeneratorProcessor.java, client/deployment/src/main/resources/templates/libraries/microprofile/auth/compositeAuthenticationProvider.qute, client/deployment/src/main/resources/templates/libraries/microprofile/auth/headersFactory.qute, client/deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/authentication/OpenApiSpecProviderTest.java, client/deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/authentication/OperationTest.java, client/runtime/src/main/java/io/quarkiverse/openapi/generator/AuthenticationRecorder.java, client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/AbstractAuthenticationPropagationHeadersFactory.java, client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/BaseCompositeAuthenticationProvider.java
Fixes #1038 
Somehow Jandex is returning duplicated `*AuthenticationMarkers` annotations from the generated `CompositeAuthenticationProvider` classes:
```java
package org.eurotransplant.immu.api.auth;
@jakarta.annotation.Priority(jakarta.ws.rs.Priorities.AUTHENTICATION)
@io.quarkiverse.openapi.generator.markers.BearerAuthenticationMarker(name="SecurityScheme", openApiSpecId="immu_2024_04_29_yml", scheme="bearer")
public class CompositeAuthenticationProvider implements jakarta.ws.rs.client.ClientRequestFilter {
@jakarta.inject.Inject
@io.quarkiverse.openapi.generator.OpenApiSpec(openApiSpecId="immu_2024_04_29_yml")
io.quarkiverse.openapi.generator.providers.BaseCompositeAuthenticationProvider compositeProvider;
@java.lang.Override …
```
=> Fix #1038 - Do not register duplicated AuthProviders SyntheticBeans

docs/modules/ROOT/pages/includes/server-getting-started.adoc, pom.xml, server/integration-tests/reactive/pom.xml, server/integration-tests/resteasy/pom.xml
This pull request closes the following issues:
* #674 (solved by https://github.com/Apicurio/apicurio-codegen/pull/318)
* #803 (solved by https://github.com/Apicurio/apicurio-codegen/pull/319)
* #985 (solved by https://github.com/Apicurio/apicurio-codegen/pull/311)
All fixes was solved by `apicurio-codegen` project, many thanks @EricWittmann for all support!
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be …
=> Upgrade apicurio-codegen

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml
<details>
<summary>
</summary> …
=> Add initial report draft

client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CommonItemConfig.java, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/SpecItemConfig.java, client/runtime/src/main/codestarts/quarkus/openapi-generator-codestart/codestart.yml, client/runtime/src/main/java/io/quarkiverse/openapi/generator/AuthConfig.java, docs/modules/ROOT/pages/includes/quarkus-openapi-generator.adoc, docs/modules/ROOT/pages/includes/quarkus-openapi-generator_quarkus.openapi-generator.adoc
Fix #1035 
<details>
<summary>
</summary> …
=> Fix #1035 - Add Interfaces to Configuration objects

client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/AbstractAuthProvider.java, client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/AuthUtils.java, client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/BasicAuthenticationProvider.java, client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/BearerAuthenticationProvider.java, client/runtime/src/test/java/io/quarkiverse/openapi/generator/providers/BasicOpenApiSpecProviderTest.java, client/runtime/src/test/java/io/quarkiverse/openapi/generator/providers/BearerOpenApiSpecProviderTest.java, docs/modules/ROOT/pages/includes/authorization-token-propagation.adoc
This PR solves **https://github.com/quarkiverse/quarkus-openapi-generator/issues/1075** and aims at adding suport for basic auth token propagation
=> Add support for basic auth propagation

docs/modules/ROOT/pages/includes/quarkus-openapi-generator-server.adoc, docs/modules/ROOT/pages/includes/quarkus-openapi-generator-server_quarkus.openapi.adoc, docs/modules/ROOT/pages/server.adoc, server/deployment/src/main/java/io/quarkiverse/openapi/server/generator/deployment/CodegenConfig.java, server/deployment/src/main/java/io/quarkiverse/openapi/server/generator/deployment/ServerCodegenConfig.java, server/deployment/src/main/java/io/quarkiverse/openapi/server/generator/deployment/codegen/ApicurioCodegenWrapper.java
<details>
<summary>
</summary> …
=> Add ServerCodegenConfig updating docs

server/deployment/src/main/java/io/quarkiverse/openapi/server/generator/deployment/ServerCodegenConfig.java, server/deployment/src/main/java/io/quarkiverse/openapi/server/generator/deployment/codegen/ApicurioOpenApiServerCodegen.java
Improve the shouldRun method for avoiding calling `trigger` method when the `inputDir` provided by `CodeGenContext` is not able to get the specification files.
Closes #1118 
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch …
=> Improve shouldRun method on Server extension

client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/GeneratorProcessor.java, client/integration-tests/override-credential-provider/pom.xml, client/integration-tests/override-credential-provider/src/main/java/io/quarkiverse/openapi/generator/it/creds/CustomCredentialsProvider.java, client/integration-tests/override-credential-provider/src/main/openapi/simple-server.yaml, client/integration-tests/override-credential-provider/src/main/resources/application.properties, client/integration-tests/override-credential-provider/src/test/java/io/quarkiverse/openapi/generator/it/creds/CustomCredentialsProviderTest.java, client/integration-tests/override-credential-provider/src/test/java/io/quarkiverse/openapi/generator/it/creds/SimpleServerMockResource.java, client/integration-tests/pom.xml, client/oidc/src/main/java/io/quarkiverse/openapi/generator/oidc/OidcAuthenticationRecorder.java, client/oidc/src/main/java/io/quarkiverse/openapi/generator/oidc/providers/OAuth2AuthenticationProvider.java
Fix #1156.
Additionally, now OAuth2 provider also has an injected CredentialsProvider.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still …
=> Fix #1156 - Move AuthProviders SyntheticBean generation to Runtime

client/integration-tests/security/src/main/java/io/quarkiverse/openapi/generator/it/security/TokenPropagationResource.java, client/integration-tests/security/src/test/java/io/quarkiverse/openapi/generator/it/security/TokenPropagationExternalServicesMock.java, client/integration-tests/security/src/test/java/io/quarkiverse/openapi/generator/it/security/TokenPropagationTest.java, client/oidc/src/main/java/io/quarkiverse/openapi/generator/oidc/providers/OAuth2AuthenticationProvider.java, client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/AbstractAuthProvider.java, client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/BasicAuthenticationProvider.java, client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/BearerAuthenticationProvider.java
Closes: #1182 
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific …
=> issue-1182: Token propagation throws java.lang.UnsupportedOperationException when adding the token to the request header parameters

client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/template/OpenApiNamespaceResolver.java, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java
Fix #1047 
<details>
<summary>
This fixes issues with generating openapi spec 3.1.0 versions on Windows, e.g. #1047 
</summary>
Please backport this to the main LTS release as well - I don't seem to be able to set a label?
I've tested this on my own simple project. 
https://github.com/jcjveraa/quarkus-openapi-generator-demoapp
Without this fix (on windows on version 2.10.0-lts): java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\(...)
With (on local build of 3.0.0-SNAPSHOT): it works fine.
No tests added 
</details>
=> Fix #1087 - Paths file when generating Java files on Windows

client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorOutputPaths.java, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/QuarkusJavaClientCodegen.java, client/deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapperTest.java, client/deployment/src/test/resources/openapi/issue-1185.json, docs/modules/ROOT/pages/includes/quarkus-openapi-generator-moqu-wiremock.adoc, docs/modules/ROOT/pages/includes/quarkus-openapi-generator-moqu-wiremock_quarkus.openapi-generator.adoc
Fix #1185 
<details>
<summary>
</summary> …
=> Fix #1185 - Add additionalProperties when type object has default value and no props

server/deployment/src/main/java/io/quarkiverse/openapi/server/generator/deployment/codegen/ApicurioOpenApiServerCodegen.java
Update the logger to reference `ApicurioOpenApiServerCodegen` instead of `ApicurioCodegenWrapper`. This ensures the correct class is logged, improving clarity and debugging accuracy.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a …
=> Fix logger initialization class reference

client/integration-tests/auth-provider/src/main/java/io/quarkiverse/openapi/generator/it/auth/provider/CustomCredentialsProvider.java, client/integration-tests/override-credential-provider/src/main/java/io/quarkiverse/openapi/generator/it/creds/CustomCredentialsProvider.java, client/oidc/src/main/java/io/quarkiverse/openapi/generator/oidc/providers/OAuth2AuthenticationProvider.java, client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/ApiKeyAuthenticationProvider.java, client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/BasicAuthenticationProvider.java, client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/BearerAuthenticationProvider.java, client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/ConfigCredentialsProvider.java, client/runtime/src/main/java/io/quarkiverse/openapi/generator/providers/CredentialsProvider.java, docs/modules/ROOT/pages/includes/quarkus-openapi-generator-moqu-wiremock.adoc, docs/modules/ROOT/pages/includes/quarkus-openapi-generator-moqu-wiremock_quarkus.openapi-generator.adoc
Fixes #1191 
<details>
<summary>
</summary> …
=> Fix #1191 - refactor CredentialsProvider return type

README.md
Added DeepWiki badge so https://deepwiki.com/quarkiverse/quarkus-openapi-generator is automatically updated
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from …
=> Added DeepWiki badge so https://deepwiki.com/quarkiverse/quarkus-openapi-generator is automatically updated

docs/modules/ROOT/pages/includes/quarkus-openapi-generator-server.adoc, docs/modules/ROOT/pages/includes/quarkus-openapi-generator-server_quarkus.openapi.adoc
This pull request adds missing documentation about the property `use-bean-validation`.
=> Add documentation about the use-bean-validation property

client/deployment/pom.xml, client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/QuarkusJavaClientCodegen.java
Fixes: https://github.com/quarkiverse/quarkus-openapi-generator/pull/1289
I set the `supportsAdditionalPropertiesWithComposedSchema` to false to keep the same behavior we already have. I didn't do a throughout review, but we already support `additionalProperties` in the schema in a composite way: https://docs.quarkiverse.io/quarkus-openapi-generator/dev/client.html#additional-properties.
So setting `additional-properties-as-attribute=true` will prevent the model from extending a `HashMap`.
See: https://github.com/OpenAPITools/openapi-generator/commit/304b3cbcaa6397a0ffc96ebe91f2678017df19fd
=> Bump to openapi-generator 7.15
